Connect to api Pull request
HERMON-1995/Book-store-project pull request #4
Opened 2023-04-05 11:50 UTC by HERMON-1995

**In this project, I connected my React & Redux application to an existing [Bookstore API](https://www.notion.so/Bookstore-API-51ea269061f849118c65c0a53e88a739) to create and remove books from a server.** Here are some of the changes: 

- Used [axios](https://axios-http.com/docs/intro) with [createAsyncThunk](https://redux-toolkit.js.org/api/createAsyncThunk) to make your HTTP requests to the backend.
- Fetched  books from the Bookstore API after the component has rendered
- Refactored the add book and remove book features to persist changes in the server

2023-04-05 12:33 UTC, Olamarx requested changes
Hi @HERMON-1995, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media2.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

## Highlights
- Linters passed ✔️ 
- Readme file professional ✔️ 
- Redux toolkit ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 12:33 UTC, Olamarx commented on src/redux/books/booksSlice.js
> +  const res = await fetch(URL);
- [ ] It is required to make all the requests with axios. Kindly consider changing fetch and make use of axios as you have used in the api-content file.

2023-04-05 12:33 UTC, Olamarx commented on src/redux/books/booksSlice.js
> +  await fetch(`${URL}/${bookId}`, {
- [ ] Same thing here as regards axios.

2023-04-05 12:33 UTC, Olamarx commented on src/redux/books/booksSlice.js
> +  const res = await fetch(URL);
- [ ] Same thing here as regards axios.

2023-04-05 12:38 UTC, HERMON-1995 commented on src/redux/books/booksSlice.js
> +  const res = await fetch(URL);
Thank you will change it right away.😊

2023-04-05 13:01 UTC, gemmen29 approved these changes
Hi @HERMON-1995, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 17:57 UTC, merged

2023-04-20 06:50 UTC, HERMON-1995 commented
Thank you for approving my project! 😄